#!/bin/sh

#复制文件夹
cp ../.viemurc .

#git上传

#touch README.md
#git init
#git add README.md
#git commit -m "first commit"
#git remote add origin git@github.com:xiaoxiaoyi/viemuconfig.git
git add *
git commit -m "auto upload"
git push -u origin master
